version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    restart: unless-stopped
    volumes:
      - "./export:/export"
      - "$IPFS_REPO_LOCATION:/data/ipfs"
    environment:
      - IPFS_PROFILE=server
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8080:8080"
